### ISSUE TITLE
Cannot convert

### ISSUE THREAD

**Issue by deathfated** [deathfated/Mark-Tugas2#2]
on startup, in Console log:
Assets\scripts\GameManager.cs(69,20): error CS0029: Cannot implicitly convert type 'int' to 'string'

VH priority, game can't start, Unity error (red alert)

**Comment by deathfated** [comment]
Found Issue!
Dalam line 69 GameManager.cs, syntax code salah untuk meng-convert variabel '_score' yang merupakan integer kedalam 'scoreText.text' yang merupakan string.

Maka, sy ganti code menggunakan syntax yang benar:
scoreText.text = $"{_score}";

**Comment by agunggm** [comment]
bisa pake _score.ToString() juga ya untuk cara yang kebih konvensional
